language: node_js
node_js:
  - 8
# keep the npm cache around to speed up installs (taken from `npm help ci`)
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - "cd optaweb-tsp-ui"
script:
  - npm run build
  - npm run lint
  #  - npm run flow check
  - npm test
