// flow-typed signature: 15d6bb0d857493a462cf2320a404d352
// flow-typed version: <<STUB>>/webstomp-client_v^1.2.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webstomp-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webstomp-client' {
  declare export class WebStomp {
    // FIXME currently not used
    // static over(ws: Object, options?: Object): WebStomp;
    // connect(headers: Object, connectCallback: Function): void;
    // connect(headers: Object, connectCallback: Function, errorCallback: Function): void;
    // connect(login, passcode, connectCallback)
    // connect(login, passcode, connectCallback, errorCallback)
    // connect(login, passcode, connectCallback, errorCallback, host)

    send(destination: string, body?: string, headers?: Object): void;
    subscribe(destination: string, callback: Function, headers?: Object): void;
  }
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webstomp-client/dist/webstomp' {
  declare module.exports: any;
}

declare module 'webstomp-client/dist/webstomp.min' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/client' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/frame' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/utils' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/webstomp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webstomp-client/dist/webstomp.js' {
  declare module.exports: $Exports<'webstomp-client/dist/webstomp'>;
}
declare module 'webstomp-client/dist/webstomp.min.js' {
  declare module.exports: $Exports<'webstomp-client/dist/webstomp.min'>;
}
declare module 'webstomp-client/src/client.js' {
  declare module.exports: $Exports<'webstomp-client/src/client'>;
}
declare module 'webstomp-client/src/frame.js' {
  declare module.exports: $Exports<'webstomp-client/src/frame'>;
}
declare module 'webstomp-client/src/utils.js' {
  declare module.exports: $Exports<'webstomp-client/src/utils'>;
}
declare module 'webstomp-client/src/webstomp.js' {
  declare module.exports: $Exports<'webstomp-client/src/webstomp'>;
}
